# Generated by Django 2.2.2 on 2019-06-08 03:17

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
