# Generated by Django 2.2.1 on 2019-05-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day06.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Stu_deatail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='day06.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('stu', models.ManyToManyField(to='day06.Student')),
            ],
        ),
    ]
