# Generated by Django 2.2.1 on 2019-05-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day06', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stu_deatail',
            new_name='Stu_detail',
        ),
    ]
