# Generated by Django 2.2.2 on 2019-06-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tb_user',
        ),
    ]
